name: CI

on:
  push:
  schedule:
    - cron: '9 * * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate HTML

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Checkout the LibreLingo tools
      uses: actions/checkout@v2
      with:
        repository: 'szabgab/LibreLingo-tools'
        path: LibreLingo-tools

    - name: Checkout the LibreLingo
      uses: actions/checkout@v2
      with:
        repository: 'kantord/LibreLingo'
        path: LibreLingo


    - name: Install dependencies
      run: |
          python -V
          #pip install -r LibreLingo-tools/requirements.txt
          pip install requests
          pip install jinja2
          cd LibreLingo/apps/librelingo_types; pip install .; cd ../../../
          cd LibreLingo/apps/librelingo_yaml_loader; pip install .; cd ../../../
          cd LibreLingo/apps/librelingo_json_export; pip install .; cd ../../../

    - name: Generate HTML pages
      run: |
          python LibreLingo-tools/generate.py --outdir docs --courses LibreLingo-tools/courses.json

    - name: Commit new files
      if: github.repository == 'szabgab/lili'
      run: |
        GIT_STATUS=$(git status --porcelain)
        GIT_COUNT=$(git status --porcelain|wc -l)
        echo $GIT_STATUS
        echo "count=$GIT_COUNT"
        git config --global user.name 'Gabor Szabo'
        git config --global user.email 'gabor@szabgab.com'
        git add docs/
        #if [ "$GIT_STATUS" != "" ] && [ "$GIT_COUNT" != "1" ]; then git commit -m "Automated Web page generation"; fi
        #if [ "$GIT_STATUS" != "" ] && [ "$GIT_COUNT" != "1" ]; then git push; fi
        if [ $GIT_COUNT -gt 1 ]; then git commit -m "Automated Web page generation"; fi
        if [ $GIT_COUNT -gt 1 ]; then git push; fi
